# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b9e4c20f3b7601e9d81bccf11dee0d1e"
name = "lcmass"
handle = "lcmass-1"
application_url = "https://suse-gives-tie-cutting.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "concludejs.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_inventory,read_metaobjects,read_orders,read_themes,write_discounts,write_inventory,write_metaobjects,write_orders,write_products,write_themes"

[auth]
redirect_urls = [
  "https://suse-gives-tie-cutting.trycloudflare.com/auth/callback",
  "https://suse-gives-tie-cutting.trycloudflare.com/auth/shopify/callback",
  "https://suse-gives-tie-cutting.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
